src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Current_Amount__c</fullName>
        <label>Current Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone_Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Current_Amount__c</fullName>
        <formula>Total_Income__c -( Total_Other_Expense__c +  Total_Developers_Payment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Developers_Payment__c</fullName>
        <label>Total Developers Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Income__c</fullName>
        <label>Total Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Other_Expense__c</fullName>
        <label>Total Other Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Company Budget</label>
    <nameField>
        <label>Company Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Developer__c.object
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone_Developer__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Per_Hour__c</fullName>
        <label>Cost Per Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Milestones Developers</relationshipLabel>
        <relationshipName>Milestones_Developers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipLabel>Milestones Developers</relationshipLabel>
        <relationshipName>Milestones_Developers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Hours__c</fullName>
        <label>Number of Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Milestone Developer</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones Developers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <summarizedField>Milestone__c.Developing_cost__c</summarizedField>
        <summaryForeignKey>Milestone__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_is_finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project is finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DataForTests.cls
/**
 * Created by tshkoda on 6/26/2020.
 */

public with sharing class DataForTests {
    public static Bill__c createBill(String recordTypeName, Milestone_Developer__c md, Developer__c developer) {
        Bill__c bill = new Bill__c(
                Due_date__c = Date.today().addDays(7),
                Amount__c = 10,
                Description__c = '1234',
                RecordTypeId = GetRecordType.getRecordType('Bill__c', recordTypeName)
        );
        if (bill.RecordType.Name == Constants.DEVELOPER_PAYMENT_RECORD_TYPE) {
            bill.Developer__c = developer.Id;
            bill.Milestone_Developer__c = md.Id;
        } else if (bill.RecordType.Name == Constants.INCOMING_PAYMENT_RECORD_TYPE || bill.RecordType.Name == Constants.MONEY_FLOW_RECORD_TYPE) {
            bill.Developer__c = developer.Id;
        }
        insert bill;
        return bill;
    }

    public static Bill__c createBill(String recordTypeName, Developer__c developer) {
        Bill__c bill = new Bill__c(
                Due_date__c = Date.today().addDays(7),
                Amount__c = 10,
                Description__c = '1234',
                RecordTypeId = GetRecordType.getRecordType('Bill__c', recordTypeName)
        );
        if (bill.RecordType.Name == Constants.INCOMING_PAYMENT_RECORD_TYPE || bill.RecordType.Name == Constants.MONEY_FLOW_RECORD_TYPE) {
            bill.Developer__c = developer.Id;
        }
        insert bill;
        return bill;
    }

    public static Developer__c createDeveloper() {
        Developer__c developer = new Developer__c(
                Name = 'TestDev'
        );
        insert developer;
        return developer;
    }

    public static Milestone_Developer__c createMilestoneDeveloper(String recordTypeName, Milestone__c milestone, Developer__c developer) {
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        for(RecordType rt: [SELECT Id, Name FROM RecordType WHERE SobjectType =: 'Milestone_Developer__c']){
            recordTypeMap.put(rt.Name, rt.Id);
        }

        Milestone_Developer__c md = new Milestone_Developer__c(
                RecordTypeId = GetRecordType.getRecordType('Milestone_Developer__c', recordTypeName),
                Name = 'Name',
                Milestone__c = milestone.Id,
                Developer__c = developer.Id
        );
        if (md.RecordTypeId == recordTypeMap.get(Constants.FIXED_COST_RECORD_TYPE)) {
            md.Developing_cost__c = 100;
        } else if (md.RecordTypeId == recordTypeMap.get(Constants.EARLY_COST_RECORD_TYPE)) {
            md.Cost_Per_Hour__c = 5;
            md.Number_of_Hours__c = 5;
        }
        insert md;
        return md;
    }

    public static Milestone__c createMilestone(String recordTypeName, Project__c project) {
        Milestone__c milestone = new Milestone__c(
                RecordTypeId = GetRecordType.getRecordType('Milestone__c', recordTypeName),
                Name = 'MilestoneName',
                Cost__c = 100000,
                Developing_cost__c = 200,
                Start_date__c = Date.today(),
                Due_date__c = Date.today().addMonths(1),
                Status__c = 'Upcoming',
                Project__c = project.Id
        );

        insert milestone;
        return milestone;
    }

    public static Project__c createProject(Customer__c customer) {
        Project__c project = new Project__c(
                Name = 'Project 1',
                Customer__c = customer.Id,
                Status__c = 'Upcoming',
                Project_is_finished__c = false
        );
        insert project;
        return project;
    }

    public static Customer__c createCustomer() {
        Customer__c customer = new Customer__c(
                Name = 'Customer1'
        );
        insert customer;
        return customer;
    }

    public static Bank_Account__c createBankAccount(Integer amount){
        Bank_Account__c ba = new Bank_Account__c(
                Name = 'Bank Account Name',
                Current_Amount__c = amount
        );
        insert ba;
        return ba;
    }
    public static Company_Budget__c createCompanyBudget(){
        Company_Budget__c cb = new Company_Budget__c(
                Name = Constants.COMPANY_NAME,
                Total_Income__c = 10000,
                Total_Developers_Payment__c = 1000,
                Total_Other_Expense__c = 10
        );
        insert cb;
        return cb;
    }
}