src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Developer__c.object
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BillControllerTest.cls
/**
 * Created by tshkoda on 6/26/2020.
 */

@IsTest
private class BillControllerTest {
    @TestSetup
    static void setup(){
        Developer__c developer = DataForTests.createDeveloper();
        DataForTests.createBill(Constants.DEVELOPER_PAYMENT_RECORD_TYPE, developer);
    }
    @IsTest
    static void checkOnGettingRecordType() {
        Bill__c bill = [SELECT Id, RecordType.Name FROM Bill__c];
//        BillController.getRecordTypeName(bill.Id);
        System.assertEquals(bill.RecordType.Name, BillController.getRecordTypeName(bill.Id));


    }
}