src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone_Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Developer__c.object
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <recordTypes>
        <fullName>Upwork</fullName>
        <active>true</active>
        <label>Upwork</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone_Developer__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Per_Hour__c</fullName>
        <label>Cost Per Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Milestones Developers</relationshipLabel>
        <relationshipName>Milestones_Developers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipLabel>Milestones Developers</relationshipLabel>
        <relationshipName>Milestones_Developers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Hours__c</fullName>
        <label>Number of Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Milestone Developer</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones Developers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Developing_cost__c</fullName>
        <label>Developing cost</label>
        <summarizedField>Milestone__c.Developing_cost__c</summarizedField>
        <summaryForeignKey>Milestone__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MilestoneDeveloperTriggerHandlerTest.cls
/**
 * Created by tshkoda on 6/30/2020.
 */

@IsTest
private class MilestoneDeveloperTriggerHandlerTest {
    @TestSetup
    static void setup() {
        Customer__c customer = DataForTests.createCustomer();
        Project__c project = DataForTests.createProject(customer);
        Developer__c developer = DataForTests.createDeveloper();
        Milestone__c milestone = DataForTests.createMilestone('Upwork', project);
        Milestone_Developer__c mdFix = DataForTests.createMilestoneDeveloper(Constants.FIXED_COST_RECORD_TYPE, milestone, developer);
        Milestone_Developer__c mdEarly = DataForTests.createMilestoneDeveloper(Constants.EARLY_COST_RECORD_TYPE, milestone, developer);
    }

    @IsTest
    static void testOnInsert() {
        Milestone_Developer__c mdFix = [
                SELECT Id, Name, Developer__r.Name, Total_Amount__c,Developing_cost__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.FIXED_COST_RECORD_TYPE
                LIMIT 1
        ];
        System.assertEquals(mdFix.Developer__r.Name, mdFix.Name);
        System.assertEquals(mdFix.Developing_cost__c, mdFix.Total_Amount__c);

        Milestone_Developer__c mdEarly = [
                SELECT Id, Name, Developer__r.Name, Cost_Per_Hour__c, Number_of_Hours__c, Total_Amount__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.EARLY_COST_RECORD_TYPE
                LIMIT 1
        ];
        System.assertEquals(mdEarly.Developer__r.Name, mdEarly.Name);
        System.assertEquals(mdEarly.Cost_Per_Hour__c * mdEarly.Number_of_Hours__c, mdEarly.Total_Amount__c);

        List<Bill__c> bill = [SELECT Id FROM Bill__c];
        System.assertNotEquals(0, bill.size());
    }

    @IsTest
    static void testOnUpdate() {
        Milestone_Developer__c mdFix = [
                SELECT Id, Name, Developer__r.Name, Total_Amount__c,Developing_cost__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.FIXED_COST_RECORD_TYPE
                LIMIT 1
        ];
        mdFix.Developing_cost__c = +10;
        update mdFix;
        mdFix = [
                SELECT Id, Name, Developer__r.Name, Total_Amount__c,Developing_cost__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.FIXED_COST_RECORD_TYPE
                LIMIT 1
        ];
        System.assertEquals(mdFix.Developing_cost__c, mdFix.Total_Amount__c);

        Milestone_Developer__c mdEarly = [
                SELECT Id, Name, Developer__r.Name, Cost_Per_Hour__c, Number_of_Hours__c, Total_Amount__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.EARLY_COST_RECORD_TYPE
                LIMIT 1
        ];
        mdEarly.Cost_Per_Hour__c = +2;
        update mdEarly;
        mdEarly = [
                SELECT Id, Name, Developer__r.Name, Cost_Per_Hour__c, Number_of_Hours__c, Total_Amount__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.EARLY_COST_RECORD_TYPE
                LIMIT 1
        ];
        System.assertEquals(mdEarly.Cost_Per_Hour__c * mdEarly.Number_of_Hours__c, mdEarly.Total_Amount__c);
    }

    @IsTest
    static void testOnDelete() {
        List<Milestone_Developer__c> milestoneDevelopers = [
                SELECT Id, Name, Developer__r.Name, Total_Amount__c,Developing_cost__c
                FROM Milestone_Developer__c
                WHERE RecordType.Name = :Constants.FIXED_COST_RECORD_TYPE
        ];
        delete milestoneDevelopers;
    }
}