src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Create_transaction__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Create transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone_Developer__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transactions__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Developer__c.object
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone_Developer__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Milestones Developers</relationshipLabel>
        <relationshipName>Milestones_Developers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone Developer</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones Developers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BillController.cls
/**
 * Created by tshkoda on 5/25/2020.
 */

public with sharing class BillController {
    @AuraEnabled
    public static Bill__c getBillById(Id recordId) {
        List<Bill__c> bills = [
                SELECT Id, Amount__c, Name, Description__c,RecordType.Developername, Developer__r.Name, Due_date__c,
                        Paid__c, Transaction__c, Milestone_Developer__r.Name, Create_transaction__c
                FROM Bill__c
                WHERE Id = :recordId
        ];
        if (!bills.isEmpty()) {
            return bills.get(0);
        }
        return null;
    }

    @AuraEnabled
    public static Bill__c saveBill(Bill__c bill) {
        // Perform isUpdateable() checking first, then
        System.debug(bill);
            update bill;
        return bill;
    }

    @AuraEnabled
    public static String getRecordTypeName(Id recordId){
        Bill__c currentBill = [SELECT RecordType.Name From Bill__c WHERE Id =: recordId];
        return currentBill.RecordType.Name;
    }
}