src/objects/Custom_Event__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Custom Events (Contact)</relationshipLabel>
        <relationshipName>Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Custom Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Custom Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomEventTriggerHandler.cls
public with sharing class CustomEventTriggerHandler extends TriggerHandler {

//    public override void afterUpdate() {
//        checkStatus();
//    }
//
//    private void checkStatus() {
//
//        List<Custom_Event__c> customEvents = trigger.new;
//
//        if (customEvents.get(0).Status__c == Constants.STATUS_APPROVED) {
//
//            Event event = new Event(
//                    Subject = Constants.SUBJECT_EVENT,
//                    StartDateTime = customEvents.get(0).Start_Time__c,
//                    EndDateTime = customEvents.get(0).End_Time__c,
//                    WhatId = Constants.ACCOUNT_MANAGER_ID,
//                    WhoId = customEvents.get(0).Contact__c,
//                    Description = customEvents.get(0).Subject__c
//            );
//            insert event;
//        }
//    }
}