src/objects/Customer__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Finished_by__c</fullName>
        <label>Finished by</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <recordTypes>
        <fullName>Upwork</fullName>
        <active>true</active>
        <label>Upwork</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Finished_by__c</fullName>
        <label>Fnished by</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_is_finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project is finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectTriggerHandlerTest.cls
/**
 * Created by tshkoda on 6/29/2020.
 */

@IsTest
private class ProjectTriggerHandlerTest {
    @TestSetup
    static void setup(){
        DataForTests.createCompanyBudget();
    }

    @IsTest
    static void checkProjectStatus() {
        Customer__c customer = DataForTests.createCustomer();
        Project__c project = DataForTests.createProject(customer);

        project.Project_is_finished__c = true;
        assertErrorOnUpdate(project, 'Unable to close the project because there are unclosed milestones');

        update project;
        project = [SELECT Id, Project_is_finished__c, Status__c FROM Project__c LIMIT 1];
        System.assertEquals(Constants.STATUS_CLOSED, project.Status__c);
        System.assertEquals(true, project.Project_is_finished__c);

        project.Project_is_finished__c = false;
        update project;
        project = [SELECT Id, Finished_by__c, Project_is_finished__c, Status__c FROM Project__c LIMIT 1];
        System.assertEquals(Constants.STATUS_INPROGRESS, project.Status__c);
        System.assertEquals(NULL, project.Finished_by__c);

        project.Status__c = Constants.STATUS_CLOSED;
        update project;
        project = [SELECT Id, Finished_by__c, Project_is_finished__c, Status__c FROM Project__c LIMIT 1];
        System.assertEquals(true, project.Project_is_finished__c);

        project.Finished_by__c = Date.today();
        update project;
        System.assertEquals(Constants.STATUS_CLOSED, project.Status__c);
        System.assertEquals(true, project.Project_is_finished__c);

        project.Finished_by__c = Date.today().addDays(5);
        update project;
        System.assertEquals(Constants.STATUS_CLOSED, project.Status__c);
    }

    private static void assertErrorOnUpdate(Project__c project, String expected) {
        Milestone__c milestone = DataForTests.createMilestone('Upwork', project);
        try {
            update project;
            System.assert(false, 'exception expected for SObject ' + project);
        } catch (Exception e) {
            System.assert(e.getMessage().contains(expected), 'message=' + e.getMessage());
        }
        milestone.Status__c = Constants.STATUS_CLOSED;
        update milestone;
    }
}